"""create products table

Revision ID: ce37684d2d10
Revises: 24994498fa2c
Create Date: 2024-05-17 20:34:55.580968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce37684d2d10'
down_revision: Union[str, None] = '24994498fa2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_user_id_fkey', 'dataset', type_='foreignkey')
    op.create_foreign_key(None, 'dataset', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.create_foreign_key('dataset_user_id_fkey', 'dataset', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
