"""create

Revision ID: 24994498fa2c
Revises: efff8f48edfe
Create Date: 2024-05-17 17:51:47.036697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24994498fa2c'
down_revision: Union[str, None] = 'efff8f48edfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('count_frames', sa.Integer(), nullable=False))
    op.add_column('dataset', sa.Column('count_classes', sa.Integer(), nullable=False))
    op.drop_column('dataset', 'description')
    op.add_column('dataset_order', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_order', 'price')
    op.add_column('dataset', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('dataset', 'count_classes')
    op.drop_column('dataset', 'count_frames')
    # ### end Alembic commands ###
