"""add columns description in product userdataset

Revision ID: 0d6318802021
Revises: 09e237911353
Create Date: 2024-05-07 13:26:02.006914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6318802021'
down_revision: Union[str, None] = '09e237911353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(length=100), nullable=False))
    op.add_column('user_dataset', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_dataset', 'description')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
